
local ignored_entity_types = {
    ["straight-rail"] = true,
    ["legacy-straight-rail"] = true,
    ["elevated-half-diagonal-rail"] = true,
    ["elevated-straight-rail"] = true,
    ["half-diagonal-rail"] = true,
    ["rail-ramp"] = true,
    ["rail-support"] = true,
    ["curved-rail"] = true,
    ["curved-rail-a"] = true,
    ["curved-rail-b"] = true,
    ["elevated-curved-rail-a"] = true,
    ["elevated-curved-rail-b"] = true,
    ["legacy-curved-rail"] = true,
    ["electric-pole"] = true,
    ["radar"] = true,
    ["solar-panel"] = true,
    ["accumulator"] = true,
    ['rail-signal'] = true,
    ['rail-chain-signal'] = true,
    ['wall'] = true,
    ['gate'] = true,
    ['car'] = true,
    ['locomotive'] = true,
    ['cargo-wagon'] = true,
    ['fluid-wagon'] = true,
    ['artillery-wagon'] = true,
    ['artillery-turret'] = true,
    ["unit"] = true,
    ["turret"] = true,
    ["unit-spawner"] = true,
}
return ignored_entity_types
